### ISSUE TITLE
allow user to edit their books

### ISSUE THREAD

**Issue by kateGalich** [kateGalich/capstone#56]
This is the editing for books on the catalogue page, be able to edit and save changes of the book.
Roughly will be complete by March 19th

**Comment by adhillon8112005** [comment]
- [x] Get the edit button on the catalogue list to go into the edit
- [x] have the books details be able to edit on the edit page
- [x] save changes to the book

**Comment by adhillon8112005** [comment]
I fixed the code so only the owner can edit the book
