### ISSUE TITLE
Allow user to delete their books

### ISSUE THREAD

**Issue by adhillon8112005** [kateGalich/capstone#57]
This is the delete button that will remove the book from the database on the catalogue list
roughly will be completed by March 19th

**Comment by adhillon8112005** [comment]
- [x] Get the delete button working the catalogue list
- [x] have it delete the book from the database
- [x] save the changes

**Comment by kateGalich** [comment]
There is one piece missing.
We should allow delete a book only to the owner.

**Comment by adhillon8112005** [comment]
I thought it already does that?

**Comment by kateGalich** [comment]
There is no check that book is deleted by it's owner here https://github.com/kateGalich/capstone/blob/main/BetterBooks/BetterBooks/Controllers/BooksController.cs#L122

**Comment by adhillon8112005** [comment]
- [x] Create a check so only the book owner can delete the book

**Comment by adhillon8112005** [comment]
Created the check to stop anyone but the owner from deleting the book
